C:\Windows\system32\wsl.exe --distribution-id {4c58d247-2fab-448d-a55f-184b5ac234c9} --cd ~
[sam@U0069NB ~]$ cat /etc/wsl.conf
[boot]
systemd=true

[user]
default=sam

[sam@U0069NB ~]$ cat /etc/wsl-distribution.conf
[oobe]
command = /usr/lib/wsl/first-setup.sh
defaultName = archlinux

[shortcut]
icon = /usr/lib/wsl/archlinux.ico


C:\Users\win>type autorun.bat
doskey winst=winget install $1
doskey kulia=\Users\win\kulia\Scripts\activate
doskey pinst=pip install --upgrade $1
doskey cd=if /i "$1"=="-" (popd) else (pushd $1)
doskey hist=doskey /history
doskey ps=powershell $1
doskey acli=arduino-cli compile --fqbn arduino:avr:uno -p COM3 $1
doskey mv=move $1
doskey aupld=arduino-cli upload -p COM3 --fqbn arduino:avr:uno $1
doskey testcom=python -m serial.tools.miniterm COM3 115200 --encoding utf-8
GOTO :EOF
#doskey acli=arduino-cli compile --fqbn arduino:avr:uno --output-dir /tmp .
#doskey aupld=arduino-cli upload -p $1 --fqbn arduino:avr:uno
#. $PROFILE
#doskey ^P=doskey /history | findstr /B /N "^" | findstr /B "1:">nul && (for /f "tokens=1,* delims=:" %%i in ('doskey /history ^| findstr /B /N "^" ^| more +%HISTOFFSET%') do (set "cmd=%%j" & set /a HISTOFFSET+=1 & call set "cmd=%%cmd%%" & if defined cmd (echo %%j) & exit /b 0)) && set HISTOFFSET=0
#doskey ^N=doskey /history | findstr /B /N "^" | findstr /B "2:">nul && (for /f "tokens=1,* delims=:" %%i in ('doskey /history ^| findstr /B /N "^" ^| more +%HISTOFFSET%') do (set "cmd=%%j" & set /a HISTOFFSET+=1 & call set "cmd=%%cmd%%" & if defined cmd (echo %%j) & exit /b 0)) && set HISTOFFSET=0
#arduino-cli board list # 先查出板子埠
:EOF
